#pragma warning disable 1591
// <auto-generated />
using Examples.EFCore.Complete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examples.EFCore.Complete.Migrations
{
	[DbContext(typeof(Context))]
	[Migration("20200423024419_Initial_Migration")]
	partial class Initial_Migration
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.3")
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("Examples.EFCore.Complete.Models.User", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int")
						.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

					b.Property<string>("FirstName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("LastName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("Visible")
						.HasColumnType("bit");

					b.HasKey("Id");

					b.ToTable("Users");
				});
#pragma warning restore 612, 618
		}
	}
}

#pragma warning restore 1591
