using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations.Design;
using Microsoft.EntityFrameworkCore.Migrations.Operations;

namespace Examples.EFCore.Complete.Migrations
{
	/// <summary>
	/// Hooks in to the generation of migration scripts to replace spaces with tabs.
	/// </summary>
	public sealed class CodeAnalysisMigrationsGenerator : CSharpMigrationsGenerator
	{
		/// <inheritdoc/>
		public CodeAnalysisMigrationsGenerator(MigrationsCodeGeneratorDependencies dependencies, CSharpMigrationsGeneratorDependencies csharpDependencies) : base(dependencies, csharpDependencies)
		{
		}

		/// <inheritdoc/>
		public override string GenerateMigration(string migrationNamespace, string migrationName, IReadOnlyList<MigrationOperation> upOperations, IReadOnlyList<MigrationOperation> downOperations)
		{
			return "// <auto-generated />"
				+ base.GenerateMigration(migrationNamespace, migrationName, upOperations, downOperations);
		}

		/// <inheritdoc/>
		public override string GenerateMetadata(string migrationNamespace, Type contextType, string migrationName, string migrationId, IModel targetModel)
		{
			return "// <auto-generated />"
				+ base.GenerateMetadata(migrationNamespace, contextType, migrationName, migrationId, targetModel);
		}
	}
}
